salmon_dir: "/data/rmccoy22/1KGP_RNASEQ/salmon_quantification/"
filtered_expression_bed: "/scratch4/battle-mccoy/sharedData/MAGE.v1.1.data/QTL_results/eQTL_results/expression_quants/TMM.filtered.TSS.MAGE.v1.1.bed.gz"
gencode: "/scratch16/rmccoy22/mtassia1/MAGE/analysis_pipeline/01_data_preparation/expression_quantification/resources/gencode.v38.annotation.gff3.gz"
metadata: "/scratch4/battle-mccoy/sharedData/MAGE.v1.1.data/sample_library_info/sequencing_library.metadata.MAGE.v1.1.txt"
